### ISSUE TITLE
entry-footer__similar, figure figure--similar are missing

### ISSUE THREAD

**Issue by EdKo2001** [antonlukin/knife-theme#190]
Hey,

I can't find those parts in the theme.

Could you help me please?

Regards,

**Comment by antonlukin** [comment]
Hi.
What are you exactly looking for? Theme styles, scripts or something else?

**Comment by EdKo2001** [comment]
https://prnt.sc/17nzsyu
https://prnt.sc/17nzwnf

**Comment by antonlukin** [comment]
backend:
https://github.com/knife-media/theme/blob/develop/app/core/modules/similar-posts.php

frontend:
https://github.com/knife-media/theme/blob/develop/src/scripts/bundle/similar-posts.js

styles:
https://github.com/knife-media/theme/blob/develop/src/styles/entry/_footer.scss#L56
https://github.com/knife-media/theme/blob/develop/src/styles/basic/_figure.scss#L251
