### ISSUE TITLE
classes are not shown in the body

### ISSUE THREAD

**Issue by EdKo2001** [antonlukin/knife-theme#191]
Hey,  I've added body class PHP code but it doesn't work (
![image](https://user-images.githubusercontent.com/53624093/124383057-87d89a00-dcdb-11eb-8e04-2eb95efe7954.png)
Could you please help?
![image](https://user-images.githubusercontent.com/53624093/124383074-a0e14b00-dcdb-11eb-946c-97cd12f281a2.png)

**Comment by antonlukin** [comment]
You should remove this filter:
https://github.com/knife-media/theme/blob/master/app/core/modules/theme-filters.php#L46
to be able to replace body class.

**Comment by EdKo2001** [comment]
Thank you.
