### ISSUE TITLE
emails from knife.media

### ISSUE THREAD

**Issue by EdKo2001** [antonlukin/knife-theme#192]
Hello, could you help?
![image](https://user-images.githubusercontent.com/53624093/124575929-e1b49d80-de5c-11eb-8e26-d89d7a2194a7.png)
Why in the emails written by knife.media?
Regards,

**Comment by antonlukin** [comment]
Thank you for your interest in the project, but I want to note that the issues of this repository do not imply user support. Please, write to me by email admin@knife.media, and I will be able to help if possible.
