### ISSUE TITLE
Search option doesn't work.

### ISSUE THREAD

**Issue by EdKo2001** [antonlukin/knife-theme#193]
![image](https://user-images.githubusercontent.com/53624093/125662785-4c44487c-c376-40c3-abcf-dd601db4fc62.png)
hello,
any suggestions?
regards,

**Comment by EdKo2001** [comment]
will anyone help me?

**Comment by antonlukin** [comment]
You should define KNIFE_GCSE const pointing to Google Custom Search Engine id.

**Comment by EdKo2001** [comment]
Hello, I've defined in the wp-config and function.php but the same.
![image](https://user-images.githubusercontent.com/53624093/126480317-f9b610f1-1dc1-4a80-b69a-edb329e3494d.png)
![image](https://user-images.githubusercontent.com/53624093/126480335-3a563c4b-8b80-4012-a4c7-e213e8066921.png)
![image](https://user-images.githubusercontent.com/53624093/126480345-4e2c4eca-4163-4182-a9a2-3dd825e54743.png)
pls help

**Comment by antonlukin** [comment]
You've used wrong constant format. Check this code, please:
https://github.com/knife-media/theme/blob/master/app/core/modules/google-search.php#L138

I have to inform you again that we do not provide support in the issues.
